
package com.flowsoft.wanda;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import userdetailsserviceimpl.wanda.flowsoft.co.UserDetailsServiceImplService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-11-19T11:49:48.441+01:00
 * Generated source version: 2.7.0
 * 
 */
public final class UserDetailsService_UserDetailsServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://com.flowsoft.wanda.UserDetailsServiceImpl", "UserDetailsServiceImplService");

    private UserDetailsService_UserDetailsServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UserDetailsServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UserDetailsServiceImplService ss = new UserDetailsServiceImplService(wsdlURL, SERVICE_NAME);
        UserDetailsService port = ss.getUserDetailsServicePort();  
        
        {
        System.out.println("Invoking findAllArticleHeader...");
        java.util.List<com.flowsoft.wanda.ArticleHeader> _findAllArticleHeader__return = port.findAllArticleHeader();
        System.out.println("findAllArticleHeader.result=" + _findAllArticleHeader__return);


        }
        {
        System.out.println("Invoking createArticle...");
        com.flowsoft.wanda.WandaUser _createArticle_wandaUser = new com.flowsoft.wanda.WandaUser();
        _createArticle_wandaUser.setCreatedTS(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2012-11-19T11:49:48.502+01:00"));
        _createArticle_wandaUser.setEmailAdress("EmailAdress1936446222");
        _createArticle_wandaUser.setEnabled(Boolean.valueOf(false));
        _createArticle_wandaUser.setFirstName("FirstName1950636100");
        _createArticle_wandaUser.setLastName("LastName-1041139397");
        _createArticle_wandaUser.setModifiedTS(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2012-11-19T11:49:48.505+01:00"));
        _createArticle_wandaUser.setPassword("Password741332153");
        _createArticle_wandaUser.setRole("Role-845390234");
        _createArticle_wandaUser.setUsername("Username-25047225");
        java.lang.String _createArticle_articleTitle = "_createArticle_articleTitle-183913";
        java.lang.String _createArticle_articleContent = "_createArticle_articleContent969537350";
        port.createArticle(_createArticle_wandaUser, _createArticle_articleTitle, _createArticle_articleContent);


        }
        {
        System.out.println("Invoking findArticleByTitle...");
        java.lang.String _findArticleByTitle_articleTitle = "_findArticleByTitle_articleTitle1282994365";
        com.flowsoft.wanda.Article _findArticleByTitle__return = port.findArticleByTitle(_findArticleByTitle_articleTitle);
        System.out.println("findArticleByTitle.result=" + _findArticleByTitle__return);


        }
        {
        System.out.println("Invoking editArticle...");
        java.lang.String _editArticle_articleTitle = "_editArticle_articleTitle249241067";
        java.lang.String _editArticle_newContent = "_editArticle_newContent-579286603";
        port.editArticle(_editArticle_articleTitle, _editArticle_newContent);


        }
        {
        System.out.println("Invoking createUser...");
        java.lang.String _createUser_username = "_createUser_username-2147408396";
        java.lang.String _createUser_password = "_createUser_password-267626502";
        java.lang.String _createUser_firstName = "_createUser_firstName-1602694857";
        java.lang.String _createUser_lastName = "_createUser_lastName-1591089160";
        java.lang.Boolean _createUser__return = port.createUser(_createUser_username, _createUser_password, _createUser_firstName, _createUser_lastName);
        System.out.println("createUser.result=" + _createUser__return);


        }
        {
        System.out.println("Invoking exist...");
        java.lang.String _exist_username = "_exist_username-589799";
        java.lang.Boolean _exist__return = port.exist(_exist_username);
        System.out.println("exist.result=" + _exist__return);


        }
        {
        System.out.println("Invoking findUserByUsername...");
        java.lang.String _findUserByUsername_username = "_findUserByUsername_username2144807354";
        com.flowsoft.wanda.WandaUser _findUserByUsername__return = port.findUserByUsername(_findUserByUsername_username);
        System.out.println("findUserByUsername.result=" + _findUserByUsername__return);


        }
        {
        System.out.println("Invoking createCategory...");
        com.flowsoft.wanda.WandaUser _createCategory_wandaUser = new com.flowsoft.wanda.WandaUser();
        _createCategory_wandaUser.setCreatedTS(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2012-11-19T11:49:48.510+01:00"));
        _createCategory_wandaUser.setEmailAdress("EmailAdress139992319");
        _createCategory_wandaUser.setEnabled(Boolean.valueOf(true));
        _createCategory_wandaUser.setFirstName("FirstName1944165925");
        _createCategory_wandaUser.setLastName("LastName-541567892");
        _createCategory_wandaUser.setModifiedTS(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2012-11-19T11:49:48.511+01:00"));
        _createCategory_wandaUser.setPassword("Password-944844148");
        _createCategory_wandaUser.setRole("Role-590132002");
        _createCategory_wandaUser.setUsername("Username1328423648");
        java.lang.String _createCategory_categoryName = "_createCategory_categoryName265818438";
        java.lang.Boolean _createCategory__return = port.createCategory(_createCategory_wandaUser, _createCategory_categoryName);
        System.out.println("createCategory.result=" + _createCategory__return);


        }
        {
        System.out.println("Invoking findAllCommentFor...");
        java.lang.String _findAllCommentFor_articleTitle = "_findAllCommentFor_articleTitle1027972475";
        java.util.List<com.flowsoft.wanda.Comment> _findAllCommentFor__return = port.findAllCommentFor(_findAllCommentFor_articleTitle);
        System.out.println("findAllCommentFor.result=" + _findAllCommentFor__return);


        }
        {
        System.out.println("Invoking findAllArticleByUsername...");
        java.lang.String _findAllArticleByUsername_username = "_findAllArticleByUsername_username803625324";
        java.util.List<com.flowsoft.wanda.Article> _findAllArticleByUsername__return = port.findAllArticleByUsername(_findAllArticleByUsername_username);
        System.out.println("findAllArticleByUsername.result=" + _findAllArticleByUsername__return);


        }
        {
        System.out.println("Invoking deleteCategory...");
        java.lang.String _deleteCategory_categoryName = "_deleteCategory_categoryName677682422";
        java.lang.String _deleteCategory_aktUsername = "_deleteCategory_aktUsername1559986556";
        port.deleteCategory(_deleteCategory_categoryName, _deleteCategory_aktUsername);


        }
        {
        System.out.println("Invoking deleteArticle...");
        java.lang.String _deleteArticle_articleTitle = "_deleteArticle_articleTitle1547610853";
        java.lang.String _deleteArticle_aktUser = "_deleteArticle_aktUser698662749";
        java.lang.String _deleteArticle__return = port.deleteArticle(_deleteArticle_articleTitle, _deleteArticle_aktUser);
        System.out.println("deleteArticle.result=" + _deleteArticle__return);


        }

        System.exit(0);
    }

}
