package com.flowsoft.wanda;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.flowsoft.domain.Article;
import com.flowsoft.domain.ArticleHeader;
import com.flowsoft.domain.Category;
import com.flowsoft.domain.Comment;
import com.flowsoft.domain.WandaUser;

/**
 * This class was generated by Apache CXF 2.7.0 2012-11-27T17:31:18.451+01:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://wanda.flowsoft.com/", name = "UserDetailsService")
@XmlSeeAlso({ ObjectFactory.class })
public interface UserDetailsService {

	@WebResult(name = "categoryList", targetNamespace = "")
	@RequestWrapper(localName = "findAllExistingCategory", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindAllExistingCategory")
	@WebMethod
	@ResponseWrapper(localName = "findAllExistingCategoryResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindAllExistingCategoryResponse")
	public java.util.List<com.flowsoft.domain.Category> findAllExistingCategory();

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "findCategoryByName", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindCategoryByName")
	@WebMethod
	@ResponseWrapper(localName = "findCategoryByNameResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindCategoryByNameResponse")
	public Category findCategoryByName(
			@WebParam(name = "categoryName", targetNamespace = "") java.lang.String categoryName);

	@RequestWrapper(localName = "commitArticle", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.CommitArticle")
	@WebMethod
	@ResponseWrapper(localName = "commitArticleResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.CommitArticleResponse")
	public void commitArticle(
			@WebParam(name = "arg0", targetNamespace = "") Article arg0);

	@WebResult(name = "articleHeaderList", targetNamespace = "")
	@RequestWrapper(localName = "findAllArticleHeader", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindAllArticleHeader")
	@WebMethod
	@ResponseWrapper(localName = "findAllArticleHeaderResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindAllArticleHeaderResponse")
	public java.util.List<ArticleHeader> findAllArticleHeader();

	@RequestWrapper(localName = "createArticle", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.CreateArticle")
	@WebMethod
	@ResponseWrapper(localName = "createArticleResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.CreateArticleResponse")
	public void createArticle(
			@WebParam(name = "owner", targetNamespace = "") WandaUser owner,
			@WebParam(name = "categoryName", targetNamespace = "") java.lang.String categoryName,
			@WebParam(name = "articleTitle", targetNamespace = "") java.lang.String articleTitle,
			@WebParam(name = "articleContent", targetNamespace = "") java.lang.String articleContent,
			@WebParam(name = "taglist", targetNamespace = "") java.util.List<java.lang.String> taglist);

	@WebResult(name = "article", targetNamespace = "")
	@RequestWrapper(localName = "findArticleByTitle", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindArticleByTitle")
	@WebMethod
	@ResponseWrapper(localName = "findArticleByTitleResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindArticleByTitleResponse")
	public Article findArticleByTitle(
			@WebParam(name = "articleTitle", targetNamespace = "") java.lang.String articleTitle);

	@RequestWrapper(localName = "editArticle", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.EditArticle")
	@WebMethod
	@ResponseWrapper(localName = "editArticleResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.EditArticleResponse")
	public void editArticle(
			@WebParam(name = "articleTitle", targetNamespace = "") java.lang.String articleTitle,
			@WebParam(name = "newContent", targetNamespace = "") java.lang.String newContent);

	@WebResult(name = "userCreationSuccess", targetNamespace = "")
	@RequestWrapper(localName = "createUser", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.CreateUser")
	@WebMethod
	@ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.CreateUserResponse")
	public java.lang.Boolean createUser(
			@WebParam(name = "username", targetNamespace = "") java.lang.String username,
			@WebParam(name = "password", targetNamespace = "") java.lang.String password,
			@WebParam(name = "firstName", targetNamespace = "") java.lang.String firstName,
			@WebParam(name = "lastName", targetNamespace = "") java.lang.String lastName);

	@WebResult(name = "exist", targetNamespace = "")
	@RequestWrapper(localName = "exist", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.Exist")
	@WebMethod
	@ResponseWrapper(localName = "existResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.ExistResponse")
	public java.lang.Boolean exist(
			@WebParam(name = "username", targetNamespace = "") java.lang.String username);

	@WebResult(name = "wandaUser", targetNamespace = "")
	@RequestWrapper(localName = "findUserByUsername", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindUserByUsername")
	@WebMethod
	@ResponseWrapper(localName = "findUserByUsernameResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindUserByUsernameResponse")
	public WandaUser findUserByUsername(
			@WebParam(name = "username", targetNamespace = "") java.lang.String username);

	@WebResult(name = "categoryCreationSuccess", targetNamespace = "")
	@RequestWrapper(localName = "createCategory", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.CreateCategory")
	@WebMethod
	@ResponseWrapper(localName = "createCategoryResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.CreateCategoryResponse")
	public java.lang.Boolean createCategory(
			@WebParam(name = "wandaUser", targetNamespace = "") WandaUser wandaUser,
			@WebParam(name = "categoryName", targetNamespace = "") java.lang.String categoryName);

	@WebResult(name = "commentList", targetNamespace = "")
	@RequestWrapper(localName = "findAllCommentFor", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindAllCommentFor")
	@WebMethod
	@ResponseWrapper(localName = "findAllCommentForResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindAllCommentForResponse")
	public java.util.List<Comment> findAllCommentFor(
			@WebParam(name = "articleTitle", targetNamespace = "") java.lang.String articleTitle);

	@WebResult(name = "articleList", targetNamespace = "")
	@RequestWrapper(localName = "findAllArticleByUsername", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindAllArticleByUsername")
	@WebMethod
	@ResponseWrapper(localName = "findAllArticleByUsernameResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindAllArticleByUsernameResponse")
	public java.util.List<Article> findAllArticleByUsername(
			@WebParam(name = "username", targetNamespace = "") java.lang.String username);

	@RequestWrapper(localName = "deleteCategory", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.DeleteCategory")
	@WebMethod
	@ResponseWrapper(localName = "deleteCategoryResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.DeleteCategoryResponse")
	public void deleteCategory(
			@WebParam(name = "categoryName", targetNamespace = "") java.lang.String categoryName,
			@WebParam(name = "aktUsername", targetNamespace = "") java.lang.String aktUsername);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "deleteArticle", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.DeleteArticle")
	@WebMethod
	@ResponseWrapper(localName = "deleteArticleResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.DeleteArticleResponse")
	public java.lang.String deleteArticle(
			@WebParam(name = "articleTitle", targetNamespace = "") java.lang.String articleTitle,
			@WebParam(name = "aktUser", targetNamespace = "") java.lang.String aktUser);
}
