package com.flowsoft.wanda;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.flowsoft.domain.Article;
import com.flowsoft.domain.Comment;
import com.flowsoft.domain.WandaUser;

/**
 * This class was generated by Apache CXF 2.7.0 2012-11-15T15:27:39.875+01:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://wanda.flowsoft.com/", name = "UserDetailsService")
@XmlSeeAlso({ ObjectFactory.class })
public interface UserDetailsService {

	@RequestWrapper(localName = "initTestDb", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.InitTestDb")
	@WebMethod
	@ResponseWrapper(localName = "initTestDbResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.InitTestDbResponse")
	public void initTestDb();

	@WebResult(name = "wandaUser", targetNamespace = "")
	@RequestWrapper(localName = "findByUsername", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindByUsername")
	@WebMethod
	@ResponseWrapper(localName = "findByUsernameResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindByUsernameResponse")
	public WandaUser findByUsername(
			@WebParam(name = "username", targetNamespace = "") java.lang.String username);

	@WebResult(name = "articleContent", targetNamespace = "")
	@RequestWrapper(localName = "getArticleContentByTitle", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.GetArticleContentByTitle")
	@WebMethod
	@ResponseWrapper(localName = "getArticleContentByTitleResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.GetArticleContentByTitleResponse")
	public java.lang.String getArticleContentByTitle(
			@WebParam(name = "articleTitle", targetNamespace = "") java.lang.String articleTitle);

	@RequestWrapper(localName = "createArticle", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.CreateArticle")
	@WebMethod
	@ResponseWrapper(localName = "createArticleResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.CreateArticleResponse")
	public void createArticle(
			@WebParam(name = "wandaUser", targetNamespace = "") WandaUser wandaUser,
			@WebParam(name = "articleTitle", targetNamespace = "") java.lang.String articleTitle,
			@WebParam(name = "articleContent", targetNamespace = "") java.lang.String articleContent);

	@WebResult(name = "articleList", targetNamespace = "")
	@RequestWrapper(localName = "findAllArticle", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindAllArticle")
	@WebMethod
	@ResponseWrapper(localName = "findAllArticleResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindAllArticleResponse")
	public java.util.List<Article> findAllArticle(
			@WebParam(name = "username", targetNamespace = "") java.lang.String username);

	@WebResult(name = "article", targetNamespace = "")
	@RequestWrapper(localName = "findArticleByTitle", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindArticleByTitle")
	@WebMethod
	@ResponseWrapper(localName = "findArticleByTitleResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindArticleByTitleResponse")
	public Article findArticleByTitle(
			@WebParam(name = "articleTitle", targetNamespace = "") java.lang.String articleTitle);

	@RequestWrapper(localName = "editArticle", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.EditArticle")
	@WebMethod
	@ResponseWrapper(localName = "editArticleResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.EditArticleResponse")
	public void editArticle(
			@WebParam(name = "articleTitle", targetNamespace = "") java.lang.String articleTitle,
			@WebParam(name = "newContent", targetNamespace = "") java.lang.String newContent);

	@WebResult(name = "creationSucces", targetNamespace = "")
	@RequestWrapper(localName = "createUser", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.CreateUser")
	@WebMethod
	@ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.CreateUserResponse")
	public java.lang.Boolean createUser(
			@WebParam(name = "username", targetNamespace = "") java.lang.String username,
			@WebParam(name = "password", targetNamespace = "") java.lang.String password,
			@WebParam(name = "firstName", targetNamespace = "") java.lang.String firstName,
			@WebParam(name = "lastName", targetNamespace = "") java.lang.String lastName);

	@WebResult(name = "exist", targetNamespace = "")
	@RequestWrapper(localName = "exist", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.Exist")
	@WebMethod
	@ResponseWrapper(localName = "existResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.ExistResponse")
	public java.lang.Boolean exist(
			@WebParam(name = "username", targetNamespace = "") java.lang.String username);

	@WebResult(name = "wandaUserList", targetNamespace = "")
	@RequestWrapper(localName = "findAllUser", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindAllUser")
	@WebMethod
	@ResponseWrapper(localName = "findAllUserResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindAllUserResponse")
	public java.util.List<WandaUser> findAllUser();

	@RequestWrapper(localName = "createCategory", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.CreateCategory")
	@WebMethod
	@ResponseWrapper(localName = "createCategoryResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.CreateCategoryResponse")
	public void createCategory(
			@WebParam(name = "wandaUser", targetNamespace = "") WandaUser wandaUser,
			@WebParam(name = "categoryName", targetNamespace = "") java.lang.String categoryName);

	@WebResult(name = "commentList", targetNamespace = "")
	@RequestWrapper(localName = "findAllCommentFor", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindAllCommentFor")
	@WebMethod
	@ResponseWrapper(localName = "findAllCommentForResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.FindAllCommentForResponse")
	public java.util.List<Comment> findAllCommentFor(
			@WebParam(name = "articleTitle", targetNamespace = "") java.lang.String articleTitle);

	@RequestWrapper(localName = "deleteCategory", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.DeleteCategory")
	@WebMethod
	@ResponseWrapper(localName = "deleteCategoryResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.DeleteCategoryResponse")
	public void deleteCategory(
			@WebParam(name = "categoryName", targetNamespace = "") java.lang.String categoryName,
			@WebParam(name = "aktUsername", targetNamespace = "") java.lang.String aktUsername);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "deleteArticle", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.DeleteArticle")
	@WebMethod
	@ResponseWrapper(localName = "deleteArticleResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.wanda.DeleteArticleResponse")
	public java.lang.String deleteArticle(
			@WebParam(name = "articleTitle", targetNamespace = "") java.lang.String articleTitle,
			@WebParam(name = "aktUser", targetNamespace = "") java.lang.String aktUser);
}
