package com.flowsoft.wanda;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0 2012-11-19T11:49:48.515+01:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://wanda.flowsoft.com/", name = "UserDetailsService")
// @XmlSeeAlso({ ObjectFactory.class })
public interface UserDetailsService {

	@WebResult(name = "articleHeaderList", targetNamespace = "")
	@RequestWrapper(localName = "findAllArticleHeader", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.domain.FindAllArticleHeader")
	@WebMethod
	@ResponseWrapper(localName = "findAllArticleHeaderResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.domain.FindAllArticleHeaderResponse")
	public java.util.List<com.flowsoft.domain.ArticleHeader> findAllArticleHeader();

	@RequestWrapper(localName = "createArticle", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.domain.CreateArticle")
	@WebMethod
	@ResponseWrapper(localName = "createArticleResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.domain.CreateArticleResponse")
	public void createArticle(
			@WebParam(name = "wandaUser", targetNamespace = "") com.flowsoft.domain.WandaUser wandaUser,
			@WebParam(name = "articleTitle", targetNamespace = "") java.lang.String articleTitle,
			@WebParam(name = "articleContent", targetNamespace = "") java.lang.String articleContent);

	@WebResult(name = "article", targetNamespace = "")
	@RequestWrapper(localName = "findArticleByTitle", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.domain.FindArticleByTitle")
	@WebMethod
	@ResponseWrapper(localName = "findArticleByTitleResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.domain.FindArticleByTitleResponse")
	public com.flowsoft.domain.Article findArticleByTitle(
			@WebParam(name = "articleTitle", targetNamespace = "") java.lang.String articleTitle);

	@RequestWrapper(localName = "editArticle", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.domain.EditArticle")
	@WebMethod
	@ResponseWrapper(localName = "editArticleResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.domain.EditArticleResponse")
	public void editArticle(
			@WebParam(name = "articleTitle", targetNamespace = "") java.lang.String articleTitle,
			@WebParam(name = "newContent", targetNamespace = "") java.lang.String newContent);

	@WebResult(name = "userCreationSuccess", targetNamespace = "")
	@RequestWrapper(localName = "createUser", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.domain.CreateUser")
	@WebMethod
	@ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.domain.CreateUserResponse")
	public java.lang.Boolean createUser(
			@WebParam(name = "username", targetNamespace = "") java.lang.String username,
			@WebParam(name = "password", targetNamespace = "") java.lang.String password,
			@WebParam(name = "firstName", targetNamespace = "") java.lang.String firstName,
			@WebParam(name = "lastName", targetNamespace = "") java.lang.String lastName);

	@WebResult(name = "exist", targetNamespace = "")
	@RequestWrapper(localName = "exist", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.domain.Exist")
	@WebMethod
	@ResponseWrapper(localName = "existResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.domain.ExistResponse")
	public java.lang.Boolean exist(
			@WebParam(name = "username", targetNamespace = "") java.lang.String username);

	@WebResult(name = "wandaUser", targetNamespace = "")
	@RequestWrapper(localName = "findUserByUsername", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.domain.FindUserByUsername")
	@WebMethod
	@ResponseWrapper(localName = "findUserByUsernameResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.domain.FindUserByUsernameResponse")
	public com.flowsoft.domain.WandaUser findUserByUsername(
			@WebParam(name = "username", targetNamespace = "") java.lang.String username);

	@WebResult(name = "categoryCreationSuccess", targetNamespace = "")
	@RequestWrapper(localName = "createCategory", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.domain.CreateCategory")
	@WebMethod
	@ResponseWrapper(localName = "createCategoryResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.domain.CreateCategoryResponse")
	public java.lang.Boolean createCategory(
			@WebParam(name = "wandaUser", targetNamespace = "") com.flowsoft.domain.WandaUser wandaUser,
			@WebParam(name = "categoryName", targetNamespace = "") java.lang.String categoryName);

	@WebResult(name = "commentList", targetNamespace = "")
	@RequestWrapper(localName = "findAllCommentFor", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.domain.FindAllCommentFor")
	@WebMethod
	@ResponseWrapper(localName = "findAllCommentForResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.domain.FindAllCommentForResponse")
	public java.util.List<com.flowsoft.domain.Comment> findAllCommentFor(
			@WebParam(name = "articleTitle", targetNamespace = "") java.lang.String articleTitle);

	@WebResult(name = "articleList", targetNamespace = "")
	@RequestWrapper(localName = "findAllArticleByUsername", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.domain.FindAllArticleByUsername")
	@WebMethod
	@ResponseWrapper(localName = "findAllArticleByUsernameResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.domain.FindAllArticleByUsernameResponse")
	public java.util.List<com.flowsoft.domain.Article> findAllArticleByUsername(
			@WebParam(name = "username", targetNamespace = "") java.lang.String username);

	@RequestWrapper(localName = "deleteCategory", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.domain.DeleteCategory")
	@WebMethod
	@ResponseWrapper(localName = "deleteCategoryResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.domain.DeleteCategoryResponse")
	public void deleteCategory(
			@WebParam(name = "categoryName", targetNamespace = "") java.lang.String categoryName,
			@WebParam(name = "aktUsername", targetNamespace = "") java.lang.String aktUsername);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "deleteArticle", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.domain.DeleteArticle")
	@WebMethod
	@ResponseWrapper(localName = "deleteArticleResponse", targetNamespace = "http://wanda.flowsoft.com/", className = "com.flowsoft.domain.DeleteArticleResponse")
	public java.lang.String deleteArticle(
			@WebParam(name = "articleTitle", targetNamespace = "") java.lang.String articleTitle,
			@WebParam(name = "aktUser", targetNamespace = "") java.lang.String aktUser);
}
